name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  REGISTRY: quay.io
  IMAGE_REPOSITORY: quay.io/mdvorak/ubi-jq

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Setup
      - name: Login to quay.io
        run: sudo podman login --username '${{ secrets.REGISTRY_USERNAME }}' --password '${{ secrets.REGISTRY_PASSWORD }}' "${REGISTRY}"

      # Get UBI version
      - name: Get UBI version
        run: |
          echo "UBI_VERSION=$(grep FROM Dockerfile | cut -d: -f2 -)" >> $GITHUB_ENV

      # Build
      - name: Build image
        run: |
          sudo podman build . \
            --label org.opencontainers.image.authors="${GITHUB_ACTOR}" \
            --label org.opencontainers.image.created="$(date --iso-8601=seconds)" \
            --label org.opencontainers.image.title="${IMAGE_REPOSITORY}" \
            --label org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}" \
            --label org.opencontainers.image.revision="${GITHUB_SHA}" \
            --label org.opencontainers.image.licenses="Unlicense" \
            --label org.opencontainers.image.description="UBI with jq installed, nothing more." \
            -t "${IMAGE_REPOSITORY}:${UBI_VERSION}"

      - name: Push image
        run: sudo podman push "${IMAGE_REPOSITORY}:${UBI_VERSION}"
